# work in progress
version: "3.1"
services:
  backend:
    image: littil-backend:latest
    container_name: littil-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - quarkus.datasource.username=littil
      - quarkus.datasource.password=littil
      - quarkus.datasource.jdb.url=jdbc:mariadb://database:3306/littil
  database:
    build: db
    container_name: littil-test-db
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: littil
      MYSQL_USER: littil
      MYSQL_PASSWORD: littil
      MYSQL_ROOT_PASSWORD: littil
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
