# work in progress
version: "3.1"

services:
  dbhost:
    build:
      dockerfile: db/Dockerfile
      context: .
    container_name: dbhost
    #hostname: dbhost
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: littil
      MYSQL_USER: littil
      MYSQL_PASSWORD: littil
      MYSQL_ROOT_PASSWORD: littil
  littil-backend:
    image: quarkus/backend-jvm # Local image for now
    container_name: littil-backend
    depends_on:
      - dbhost
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://dbhost:3306/littil
      - QUARKUS_DATASOURCE_USERNAME=littil
      - QUARKUS_DATASOURCE_PASSWORD=littil
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_TENANT=${OIDC_TENANT}
      - M2M_CLIENT_ID=${M2M_CLIENT_ID}
      - M2M_CLIENT_SECRET=${M2M_CLIENT_SECRET}
      - SMTP_HOST=smtp-stub.local
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
    ports:
      - "8080:8080"
  littil-frontend:
    image: littil-frontend # Local image for now
    depends_on:
      - littil-backend
    env_file:
      - .env
    ports:
      - "80:80"
  cypress:
    image: 'cypress/included:12.3.0'
    container_name: cypress
    env_file:
      - .env
    depends_on:
     - littil-frontend
    volumes:
      - ./cypress:/cypress
      - ./cypress.env.json:/cypress.env.json
      - ./cypress.docker.config.js:/cypress.config.js
    entrypoint: "cypress run --headless --browser electron --reporter junit --reporter-options mochaFile=./cypress/test-output-[hash].xml"
